<?php

return [
    /*
     |--------------------------------------------------------------------------
     | Routing configuration
     |--------------------------------------------------------------------------
     |
     | This configuration is used to determine the routing behavior of the
     | Server notifications handler endpoint.
     |
     | You can find more information on documentation.
     | @see https://imdhemy.com/laravel-iap-docs/docs/get-started/routing
     */
    'routing' => [
        'signed' => false,
        'middleware' => [],
        'prefix' => 'v1',
    ],

    /*
     |--------------------------------------------------------------------------
     | Google Play Default Package name
     |--------------------------------------------------------------------------
     |
     | This value is the default package name used when the package name is not
     | provided while verifying the receipts.
     |
     */
    'google_play_package_name' => env('GOOGLE_PLAY_PACKAGE_NAME', 'com.some.thing'),

    /*
     |--------------------------------------------------------------------------
     | App Store Password
     |--------------------------------------------------------------------------
     |
     | This value is the app-specific share password generated by the app store.
     | @see https://imdhemy.com/laravel-iap-docs/docs/credentials/app-store
     |
     */
    'appstore_password' => env('SK_APP_PASSWORD', ''),

    /*
     |--------------------------------------------------------------------------
     | Event Listeners
     |--------------------------------------------------------------------------
     |
     | This configuration is used to determine the event listeners that will be
     | registered with the application.
     | You can find a list of all available events of the documentation
     |
     | @see https://imdhemy.com/laravel-iap-docs/docs/server-notifications/event-list
     | @see https://imdhemy.com/laravel-iap-docs/docs/get-started/event-listeners
     |
    */
    'eventListeners' => [
        /*
         |--------------------------------------------------------------------------
         | App Store Events
         |--------------------------------------------------------------------------
         |
         | These event listeners are triggered when a new notification is received from App Store.
         | @see https://imdhemy.com/laravel-iap-docs/docs/server-notifications/event-list#app-store-events
         |
         */
        \Imdhemy\Purchases\Events\AppStore\DidChangeRenewalPref::class => [
            \App\Listeners\AppStore\DidChangeRenewalPref::class
        ],
        \Imdhemy\Purchases\Events\AppStore\DidChangeRenewalStatus::class => [
            \App\Listeners\AppStore\DidChangeRenewalStatus::class
        ],
        \Imdhemy\Purchases\Events\AppStore\DidFailToRenew::class => [
            \App\Listeners\AppStore\DidFailToRenew::class
        ],
        \Imdhemy\Purchases\Events\AppStore\DidRenew::class => [
            \App\Listeners\AppStore\DidRenew::class
        ],
        \Imdhemy\Purchases\Events\AppStore\Expired::class => [
            \App\Listeners\AppStore\Expired::class
        ],
        \Imdhemy\Purchases\Events\AppStore\GracePeriodExpired::class => [
            \App\Listeners\AppStore\GracePeriodExpired::class
        ],
        \Imdhemy\Purchases\Events\AppStore\OfferRedeemed::class => [
            \App\Listeners\AppStore\OfferRedeemed::class
        ],
        \Imdhemy\Purchases\Events\AppStore\PriceIncrease::class => [
            \App\Listeners\AppStore\PriceIncrease::class
        ],
        \Imdhemy\Purchases\Events\AppStore\Refund::class => [
            \App\Listeners\AppStore\Refund::class
        ],
        \Imdhemy\Purchases\Events\AppStore\RenewalExtended::class => [
            \App\Listeners\AppStore\RenewalExtended::class
        ],
        \Imdhemy\Purchases\Events\AppStore\Revoke::class => [
            \App\Listeners\AppStore\Revoke::class
        ],
        \Imdhemy\Purchases\Events\AppStore\Subscribed::class => [
            \App\Listeners\AppStore\Subscribed::class
        ],

        \Imdhemy\Purchases\Events\AppStore\Cancel::class => [],
        \Imdhemy\Purchases\Events\AppStore\DidRecover::class => [],
        \Imdhemy\Purchases\Events\AppStore\InitialBuy::class => [],
        \Imdhemy\Purchases\Events\AppStore\InteractiveRenewal::class => [],
        \Imdhemy\Purchases\Events\AppStore\PriceIncreaseConsent::class => [],

        /*
         |--------------------------------------------------------------------------
         | Google Play Events
         |--------------------------------------------------------------------------
         |
         | These event listeners are triggered when a new notification is received from Google Play
         | @see @see https://imdhemy.com/laravel-iap-docs/docs/server-notifications/event-list#google-play-events
         */
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionPurchased::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionRenewed::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionInGracePeriod::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionExpired::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionCanceled::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionPaused::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionRestarted::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionDeferred::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionRevoked::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionOnHold::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionRecovered::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionPauseScheduleChanged::class => [],
        \Imdhemy\Purchases\Events\GooglePlay\SubscriptionPriceChangeConfirmed::class => [],
    ],
];
