[supervisord]
nodaemon=true ; start in foreground if true; default false
user=root ; setuid to this UNIX account to run the program
logfile=/var/log/supervisord.log ; main log file; default $CWD/supervisord.log
logfile_maxbytes=0 ; disable rotation; logfile symlinks to /dev/stdout (non-seekable)
pidfile=/run/supervisord.pid ; supervisord pidfile; default supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm
numprocs=1
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm_consumer.err.log
stderr_logfile_maxbytes=0
stdout_logfile=/var/log/php-fpm_consumer.out.log
stdout_logfile_maxbytes=0
user=root
priority=100

[include]
files = /etc/supervisor/supervisord.d/*.conf
