[supervisord]
nodaemon=false ; runs as a backgrounded child of the FrankenPHP entrypoint
user=root ; setuid to this UNIX account to run the program
logfile=/var/log/supervisord.log ; main log file; default $CWD/supervisord.log
logfile_maxbytes=0 ; disable rotation; logfile symlinks to /dev/stdout (non-seekable)
pidfile=/run/supervisord.pid ; supervisord pidfile; default supervisord.pid

[include]
files = /etc/supervisor/supervisord.d/*.conf
